apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  labels: {{ include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-exporter
spec:
  type: ClusterIP
  ports:
  - port: 9100
    targetPort: 9100
    protocol: TCP
    name: http-metrics
  selector: {{ include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-exporter
