
apiVersion: v1
kind: Secret
metadata:
  name: grafana-auth
  labels: {{ include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
data:
  GF_SECURITY_ADMIN_USER: {{ .Values.auth.admin.username | b64enc }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.auth.admin.password | b64enc }}