apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: owdev
    meta.helm.sh/release-namespace: openwhisk
  creationTimestamp: "2023-02-21T09:23:11Z"
  labels:
    app: owdev-openwhisk
    app.kubernetes.io/managed-by: Helm
    chart: openwhisk-1.0.1
    heritage: Helm
    name: owdev-redis
    release: owdev
  name: owdev-redis
  namespace: openwhisk
  resourceVersion: "14286"
  uid: 96dea8c4-b2e4-4e7c-9c09-bd3354611819
spec:
  clusterIP: 10.43.119.251
  clusterIPs:
  - 10.43.119.251
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: owdev-redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}