apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: owdev
    meta.helm.sh/release-namespace: openwhisk
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: liquidfaas.cloud
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  creationTimestamp: "2023-02-21T09:23:10Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: owdev-openwhisk
    app.kubernetes.io/managed-by: Helm
    chart: openwhisk-1.0.1
    heritage: Helm
    release: owdev
  name: owdev-couchdb-pvc
  namespace: openwhisk
  resourceVersion: "14566"
  uid: c06b59e9-1d94-42c9-8d17-e9f2974a11f4
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pvc-c06b59e9-1d94-42c9-8d17-e9f2974a11f4
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  phase: Bound