apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
    meta.helm.sh/release-name: owdev
    meta.helm.sh/release-namespace: openwhisk
  creationTimestamp: "2023-02-21T09:23:11Z"
  generation: 1
  labels:
    app: owdev-openwhisk
    app.kubernetes.io/managed-by: Helm
    chart: openwhisk-1.0.1
    heritage: Helm
    name: owdev-gen-certs
    release: owdev
  name: owdev-gen-certs
  namespace: openwhisk
  resourceVersion: "14595"
  uid: 5019b291-8f20-4dda-868c-235b4cb5e742
spec:
  backoffLimit: 3
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 5019b291-8f20-4dda-868c-235b4cb5e742
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: owdev-openwhisk
        chart: openwhisk-1.0.1
        controller-uid: 5019b291-8f20-4dda-868c-235b4cb5e742
        heritage: Helm
        job-name: owdev-gen-certs
        name: owdev-gen-certs
        release: owdev
      name: owdev-gen-certs
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - set -e; . /task/gencerts.sh
        env:
        - name: NGINX_CERT_SECRET
          value: owdev-nginx
        - name: WHISK_API_HOST_NAME
          valueFrom:
            configMapKeyRef:
              key: whisk_external_api_host_name
              name: owdev-whisk.config
        image: openwhisk/ow-utils:ef725a6
        imagePullPolicy: IfNotPresent
        name: gen-certs
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /task/gencerts.sh
          name: task-dir
          subPath: gencerts.sh
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: owdev-init-sa
      serviceAccountName: owdev-init-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: owdev-gen-certs
        name: task-dir
status:
  completionTime: "2023-02-21T09:23:57Z"
  conditions:
  - lastProbeTime: "2023-02-21T09:23:57Z"
    lastTransitionTime: "2023-02-21T09:23:57Z"
    status: "True"
    type: Complete
  ready: 0
  startTime: "2023-02-21T09:23:11Z"
  succeeded: 1
  uncountedTerminatedPods: {}