apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: owdev
    meta.helm.sh/release-namespace: openwhisk
  creationTimestamp: "2023-02-21T09:23:11Z"
  labels:
    app: owdev-openwhisk
    app.kubernetes.io/managed-by: Helm
    chart: openwhisk-1.0.1
    heritage: Helm
    name: owdev-couchdb
    release: owdev
  name: owdev-couchdb
  namespace: openwhisk
  resourceVersion: "14259"
  uid: e12bc9ef-e7c0-498b-a104-d1b27f17d9f4
spec:
  clusterIP: 10.43.141.101
  clusterIPs:
  - 10.43.141.101
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: couchdb
    port: 5984
    protocol: TCP
    targetPort: 5984
  selector:
    name: owdev-couchdb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}