apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: owdev
    meta.helm.sh/release-namespace: openwhisk
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: liquidfaas.cloud
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  creationTimestamp: "2023-02-21T09:23:10Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: owdev-openwhisk
    app.kubernetes.io/managed-by: Helm
    chart: openwhisk-1.0.1
    heritage: Helm
    release: owdev
  name: owdev-zookeeper-pvc-datalog
  namespace: openwhisk
  resourceVersion: "14634"
  uid: 6a67b9b8-d68f-4ff8-acb2-2dcbb9dac019
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pvc-6a67b9b8-d68f-4ff8-acb2-2dcbb9dac019
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 256Mi
  phase: Bound