apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: owdev
    meta.helm.sh/release-namespace: openwhisk
  creationTimestamp: "2023-02-21T09:23:11Z"
  generation: 1
  labels:
    app: owdev-openwhisk
    app.kubernetes.io/managed-by: Helm
    chart: openwhisk-1.0.1
    heritage: Helm
    name: owdev-couchdb
    release: owdev
  name: owdev-couchdb
  namespace: openwhisk
  resourceVersion: "14663"
  uid: 9df81ba6-ee1c-451f-aee3-944a279b028e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: owdev-couchdb
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: owdev-openwhisk
        chart: openwhisk-1.0.1
        heritage: Helm
        name: owdev-couchdb
        release: owdev
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: openwhisk-role
                operator: NotIn
                values:
                - invoker
            weight: 100
          - preference:
              matchExpressions:
              - key: openwhisk-role
                operator: In
                values:
                - core
            weight: 80
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - owdev-couchdb
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              key: db_username
              name: owdev-db.auth
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db_password
              name: owdev-db.auth
        - name: NODENAME
          value: couchdb0
        image: apache/couchdb:2.3
        imagePullPolicy: IfNotPresent
        name: couchdb
        ports:
        - containerPort: 5984
          name: couchdb
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/couchdb/data
          name: database-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: openwhisk-role
        operator: Equal
        value: core
      volumes:
      - name: database-storage
        persistentVolumeClaim:
          claimName: owdev-couchdb-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-21T09:24:07Z"
    lastUpdateTime: "2023-02-21T09:24:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-02-21T09:23:11Z"
    lastUpdateTime: "2023-02-21T09:24:07Z"
    message: ReplicaSet "owdev-couchdb-657c65c9cb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1