apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: owdev
    meta.helm.sh/release-namespace: openwhisk
  creationTimestamp: "2023-02-21T09:23:11Z"
  generation: 1
  labels:
    app: owdev-openwhisk
    app.kubernetes.io/managed-by: Helm
    chart: openwhisk-1.0.1
    heritage: Helm
    name: owdev-nginx
    release: owdev
  name: owdev-nginx
  namespace: openwhisk
  resourceVersion: "14811"
  uid: 4f6879be-477d-4eb9-9083-d08570ecd3ea
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: owdev-nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: owdev-openwhisk
        chart: openwhisk-1.0.1
        heritage: Helm
        name: owdev-nginx
        release: owdev
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: openwhisk-role
                operator: NotIn
                values:
                - invoker
            weight: 100
          - preference:
              matchExpressions:
              - key: openwhisk-role
                operator: In
                values:
                - edge
            weight: 80
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - owdev-nginx
            topologyKey: kubernetes.io/hostname
      containers:
      - image: nginx:1.21.1
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-conf
          subPath: nginx.conf
        - mountPath: /etc/nginx/certs
          name: nginx-certs
        - mountPath: /logs
          name: logs
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - 'result=1; until [ $result -eq 0 ]; do echo ''Checking controller readiness'';
          wget -T 5 --spider $READINESS_URL; result=$?; sleep 1; done; echo ''Success:
          controller is ready'''
        env:
        - name: READINESS_URL
          value: http://owdev-controller.openwhisk.svc.cluster.local:8080/ping
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        name: wait-for-controller
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: openwhisk-role
        operator: Equal
        value: edge
      volumes:
      - name: nginx-certs
        secret:
          defaultMode: 420
          secretName: owdev-nginx
      - configMap:
          defaultMode: 420
          name: owdev-nginx
        name: nginx-conf
      - emptyDir: {}
        name: logs
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-21T09:28:06Z"
    lastUpdateTime: "2023-02-21T09:28:06Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-02-21T09:23:11Z"
    lastUpdateTime: "2023-02-21T09:28:06Z"
    message: ReplicaSet "owdev-nginx-6dbf6d5996" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1