apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: owdev
    meta.helm.sh/release-namespace: openwhisk
  creationTimestamp: "2023-02-21T09:23:11Z"
  generation: 1
  labels:
    app: owdev-openwhisk
    app.kubernetes.io/managed-by: Helm
    chart: openwhisk-1.0.1
    heritage: Helm
    name: owdev-redis
    release: owdev
  name: owdev-redis
  namespace: openwhisk
  resourceVersion: "14669"
  uid: f4299f61-a01e-4977-bea3-266ea94d450f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: owdev-redis
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: owdev-openwhisk
        chart: openwhisk-1.0.1
        heritage: Helm
        name: owdev-redis
        release: owdev
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: openwhisk-role
                operator: NotIn
                values:
                - invoker
            weight: 100
          - preference:
              matchExpressions:
              - key: openwhisk-role
                operator: In
                values:
                - core
            weight: 80
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - owdev-redis
            topologyKey: kubernetes.io/hostname
      containers:
      - image: redis:4.0
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: redis-data
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - chown
        - -v
        - -R
        - 999:999
        - /data
        image: busybox:latest
        imagePullPolicy: Always
        name: redis-init
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: redis-data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: openwhisk-role
        operator: Equal
        value: core
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: owdev-redis-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-21T09:24:08Z"
    lastUpdateTime: "2023-02-21T09:24:08Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-02-21T09:23:11Z"
    lastUpdateTime: "2023-02-21T09:24:08Z"
    message: ReplicaSet "owdev-redis-756f879b8b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1