apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: owdev
    meta.helm.sh/release-namespace: openwhisk
  creationTimestamp: "2023-02-21T09:23:11Z"
  generation: 1
  labels:
    app: owdev-openwhisk
    app.kubernetes.io/managed-by: Helm
    chart: openwhisk-1.0.1
    heritage: Helm
    name: owdev-zookeeper
    release: owdev
  name: owdev-zookeeper
  namespace: openwhisk
  resourceVersion: "14690"
  uid: 7bd0535f-aeaf-462b-82d7-3ebaed383569
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: owdev-zookeeper
  serviceName: owdev-zookeeper
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: owdev-openwhisk
        chart: openwhisk-1.0.1
        heritage: Helm
        name: owdev-zookeeper
        release: owdev
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: openwhisk-role
                operator: NotIn
                values:
                - invoker
            weight: 100
          - preference:
              matchExpressions:
              - key: openwhisk-role
                operator: In
                values:
                - core
            weight: 80
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - owdev-zookeeper
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - /bin/bash
        - -c
        - hostname -s | awk -F '-' '{print $NF}'> /data/myid; cat /data/myid; cat
          /conf/zoo.cfg; zkServer.sh start-foreground
        image: zookeeper:3.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 2181
          timeoutSeconds: 1
        name: zookeeper
        ports:
        - containerPort: 2181
          name: zookeeper
          protocol: TCP
        - containerPort: 2888
          name: server
          protocol: TCP
        - containerPort: 3888
          name: leader-election
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - echo ruok | nc -w 1 localhost 2181 | grep imok
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /conf
          name: zk-config
        - mountPath: /data
          name: owdev-zookeeper-pvc-data
        - mountPath: /datalog
          name: owdev-zookeeper-pvc-datalog
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: openwhisk-role
        operator: Equal
        value: core
      volumes:
      - configMap:
          defaultMode: 420
          name: owdev-zookeeper
        name: zk-config
      - name: owdev-zookeeper-pvc-data
        persistentVolumeClaim:
          claimName: owdev-zookeeper-pvc-data
      - name: owdev-zookeeper-pvc-datalog
        persistentVolumeClaim:
          claimName: owdev-zookeeper-pvc-datalog
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  availableReplicas: 1
  collisionCount: 0
  currentReplicas: 1
  currentRevision: owdev-zookeeper-59dc57cbb8
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: owdev-zookeeper-59dc57cbb8
  updatedReplicas: 1