apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: owdev
    meta.helm.sh/release-namespace: openwhisk
  creationTimestamp: "2023-02-21T09:23:11Z"
  labels:
    app: owdev-openwhisk
    app.kubernetes.io/managed-by: Helm
    chart: openwhisk-1.0.1
    heritage: Helm
    name: owdev-zookeeper
    release: owdev
  name: owdev-zookeeper
  namespace: openwhisk
  resourceVersion: "14257"
  uid: 49463db4-d9ca-499b-bbbd-9bb260fc6d84
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: zookeeper
    port: 2181
    protocol: TCP
    targetPort: 2181
  - name: server
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: leader-election
    port: 3888
    protocol: TCP
    targetPort: 3888
  selector:
    name: owdev-zookeeper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}