apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
    meta.helm.sh/release-name: owdev
    meta.helm.sh/release-namespace: openwhisk
  creationTimestamp: "2023-02-21T09:23:11Z"
  generation: 1
  labels:
    app: owdev-openwhisk
    app.kubernetes.io/managed-by: Helm
    chart: openwhisk-1.0.1
    heritage: Helm
    name: owdev-init-couchdb
    release: owdev
  name: owdev-init-couchdb
  namespace: openwhisk
  resourceVersion: "14751"
  uid: 3d9f75cf-c381-4e4a-88de-c8f16864d567
spec:
  backoffLimit: 3
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 3d9f75cf-c381-4e4a-88de-c8f16864d567
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: owdev-openwhisk
        chart: openwhisk-1.0.1
        controller-uid: 3d9f75cf-c381-4e4a-88de-c8f16864d567
        heritage: Helm
        job-name: owdev-init-couchdb
        name: owdev-init-couchdb
        release: owdev
      name: owdev-init-couchdb
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - set -e; . /task/initdb.sh
        env:
        - name: DB_PROTOCOL
          valueFrom:
            configMapKeyRef:
              key: db_protocol
              name: owdev-db.config
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: db_host
              name: owdev-db.config
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: db_port
              name: owdev-db.config
        - name: DB_PREFIX
          valueFrom:
            configMapKeyRef:
              key: db_prefix
              name: owdev-db.config
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              key: db_username
              name: owdev-db.auth
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db_password
              name: owdev-db.auth
        - name: NODENAME
          value: couchdb0
        - name: OW_GIT_TAG_OPENWHISK
          value: ef725a653ab112391f79c274d8e3dcfb915d59a3
        image: openwhisk/ow-utils:ef725a6
        imagePullPolicy: IfNotPresent
        name: init-couchdb
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /task/initdb.sh
          name: task-dir
          subPath: initdb.sh
        - mountPath: /etc/whisk-auth
          name: whisk-auth
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: owdev-init-couchdb
        name: task-dir
      - name: whisk-auth
        secret:
          defaultMode: 420
          secretName: owdev-whisk.auth
status:
  completionTime: "2023-02-21T09:26:38Z"
  conditions:
  - lastProbeTime: "2023-02-21T09:26:38Z"
    lastTransitionTime: "2023-02-21T09:26:38Z"
    status: "True"
    type: Complete
  ready: 0
  startTime: "2023-02-21T09:23:11Z"
  succeeded: 1
  uncountedTerminatedPods: {}