apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
    meta.helm.sh/release-name: owdev
    meta.helm.sh/release-namespace: openwhisk
  creationTimestamp: "2023-02-21T09:23:11Z"
  generation: 1
  labels:
    app: owdev-openwhisk
    app.kubernetes.io/managed-by: Helm
    chart: openwhisk-1.0.1
    heritage: Helm
    name: owdev-install-packages
    release: owdev
  name: owdev-install-packages
  namespace: openwhisk
  resourceVersion: "14883"
  uid: 1868d735-99dd-4f8e-b38d-c6c4474eb473
spec:
  backoffLimit: 3
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 1868d735-99dd-4f8e-b38d-c6c4474eb473
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: owdev-openwhisk
        chart: openwhisk-1.0.1
        controller-uid: 1868d735-99dd-4f8e-b38d-c6c4474eb473
        heritage: Helm
        job-name: owdev-install-packages
        name: owdev-install-packages
        release: owdev
      name: owdev-install-packages
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - set -e; . /task/myTask.sh
        env:
        - name: WHISK_AUTH
          valueFrom:
            secretKeyRef:
              key: system
              name: owdev-whisk.auth
        - name: WHISK_API_HOST
          valueFrom:
            configMapKeyRef:
              key: whisk_internal_api_host_nameAndPort
              name: owdev-whisk.config
        - name: WHISK_API_HOST_URL
          valueFrom:
            configMapKeyRef:
              key: whisk_internal_api_host_url
              name: owdev-whisk.config
        - name: WHISK_SYSTEM_NAMESPACE
          valueFrom:
            configMapKeyRef:
              key: whisk_system_namespace
              name: owdev-whisk.config
        - name: WHISK_API_GATEWAY_HOST_V2
          value: http://owdev-apigateway.openwhisk.svc.cluster.local:9000/v2
        - name: PROVIDER_DB_HOST
          valueFrom:
            configMapKeyRef:
              key: db_host
              name: owdev-db.config
        - name: PROVIDER_DB_PROTOCOL
          valueFrom:
            configMapKeyRef:
              key: db_protocol
              name: owdev-db.config
        - name: PROVIDER_DB_PORT
          valueFrom:
            configMapKeyRef:
              key: db_port
              name: owdev-db.config
        - name: PROVIDER_DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: db_username
              name: owdev-db.auth
        - name: PROVIDER_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db_password
              name: owdev-db.auth
        - name: ALARM_DB_PREFIX
          value: alm
        - name: KAFKA_DB_PREFIX
          value: kp
        - name: OW_INSTALL_ALARM_PROVIDER
          value: "yes"
        - name: OW_INSTALL_KAFKA_PROVIDER
          value: "yes"
        - name: OW_GIT_TAG_OPENWHISK
          value: ef725a653ab112391f79c274d8e3dcfb915d59a3
        - name: OW_GIT_TAG_OPENWHISK_CATALOG
          value: 1.0.0
        - name: OW_GIT_TAG_OPENWHISK_PACKAGE_ALARMS
          value: 2.3.0
        - name: OW_GIT_TAG_OPENWHISK_PACKAGE_KAFKA
          value: 2.1.0
        image: openwhisk/ow-utils:ef725a6
        imagePullPolicy: IfNotPresent
        name: install-packages
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /task/myTask.sh
          name: task-dir
          subPath: myTask.sh
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - 'echo 0 > /tmp/count.txt; while true; do echo ''waiting for healthy invoker'';
          wget -T 5 -qO /tmp/count.txt --no-check-certificate "$READINESS_URL"; NUM_HEALTHY_INVOKERS=$(cat
          /tmp/count.txt); if [ $NUM_HEALTHY_INVOKERS -gt 0 ]; then echo "Success:
          there are $NUM_HEALTHY_INVOKERS healthy invokers"; break; fi; echo ''...not
          ready yet; sleeping 3 seconds before retry''; sleep 3; done;'
        env:
        - name: READINESS_URL
          value: http://owdev-controller.openwhisk.svc.cluster.local:8080/invokers/healthy/count 
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        name: wait-for-healthy-invoker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: owdev-install-packages-cm
        name: task-dir
status:
  completionTime: "2023-02-21T09:29:38Z"
  conditions:
  - lastProbeTime: "2023-02-21T09:29:38Z"
    lastTransitionTime: "2023-02-21T09:29:38Z"
    status: "True"
    type: Complete
  ready: 0
  startTime: "2023-02-21T09:23:11Z"
  succeeded: 1
  uncountedTerminatedPods: {