apiVersion: v1
data:
  db_password: c29tZV9wYXNzdzByZA==
  db_username: d2hpc2tfYWRtaW4=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: owdev
    meta.helm.sh/release-namespace: openwhisk
  creationTimestamp: "2023-02-21T09:23:10Z"
  labels:
    app: owdev-openwhisk
    app.kubernetes.io/managed-by: Helm
    chart: openwhisk-1.0.1
    heritage: Helm
    release: owdev
  name: owdev-db.auth
  namespace: openwhisk
  resourceVersion: "14227"
  uid: cec9fb92-7d53-4dc3-9a02-5c77b26b6090
type: Opaque