apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  namespace: mosquitto
spec:
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
      - name: publisher
        image: giuliabianchi1408/publisher:latest
        ports:
        - containerPort: 5000