apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  namespace: mosquitto
spec:
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      containers:
      - name: subscriber
        image: giuliabianchi1408/subscriber:latest
        ports:
        - containerPort: 5000