apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels: {{ include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  ports:
  - name: http-web
    port: 9090
    targetPort: 9090
  publishNotReadyAddresses: false
  selector:
    app: prometheus
    app.kubernetes.io/component: prometheus
  type: "ClusterIP"
