apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  labels: {{ include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  endpoints:
  - port: http-web
    path: "/metrics"
  selector:
    matchLabels: {{ include "app.labels" . | nindent 6 }}
      app.kubernetes.io/component: prometheus
