{{- if .Capabilities.APIVersions.Has "integreatly.org/v1alpha1/GrafanaDataSource" }}
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus
  labels: {{ include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  name: prometheus
  datasources:
  - access: "proxy"
    isDefault: true
    name: "prometheus"
    type: "prometheus"
    url: "http://prometheus:9090"
    version: 1
{{- end }}