apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: openwhisk
spec:
  endpoints:
  - port: http
    path: "/metrics"
  selector:
    matchLabels: 
      name: openwhisk-controller
