apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-operator
  labels: {{ include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
rules:
- apiGroups: [""]
  resources: ["configmaps", "persistentvolumeclaims", "secrets", "serviceaccounts", "services"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments", "deployments/finalizers"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-operator
  labels: {{ include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana-operator
subjects:
- kind: ServiceAccount
  name: grafana-operator
  namespace: {{ .Release.Namespace }}
