apiVersion: v1
kind: Service
metadata:
  name: grafana-operator
  labels: {{ include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: metrics
  selector: {{ include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
