apiVersion: v2
description: Apache OpenWhisk is an open source serverless cloud platform
home: https://openwhisk.apache.org
icon: https://raw.githubusercontent.com/apache/openwhisk/682eb5b62ee6ba8017ab54226c2ace3637f4f1ec/docs/images/whisk_icon_full-color_with_tm_64x64-300dpi.png
keywords:
- Apache OpenWhisk
- amd64
kubeVersion: '>=v1.14.0-r0'
maintainers:
- email: dev@openwhisk.apache.org
  name: Apache OpenWhisk Community
name: openwhisk
type: application
version: 1.0.0
