apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-state-metrics-exporter
  labels: {{ include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: kube-state-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-state-metrics-exporter
subjects:
- kind: ServiceAccount
  name: kube-state-metrics-exporter
  namespace: {{ .Release.Namespace }}
