apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-operator
  labels: {{ include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus-operator
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "app.labels" . | nindent 6 }}
      app.kubernetes.io/component: prometheus-operator
  template:
    metadata:
      labels: {{ include "app.labels" . | nindent 8 }}
        app.kubernetes.io/component: prometheus-operator
      annotations:
        generation: "{{ .Release.Revision }}"
    spec:
      containers:
      - name: kube-prometheus-stack
        image: "quay.io/prometheus-operator/prometheus-operator:v0.63.0"
        imagePullPolicy: "IfNotPresent"
        args:
        - --kubelet-service=kube-system/prometheus-operator-kube-p-kubelet
        - --localhost=127.0.0.1
        - --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.63.0
        - --config-reloader-cpu-request=200m
        - --config-reloader-cpu-limit=200m
        - --config-reloader-memory-request=50Mi
        - --config-reloader-memory-limit=50Mi
        - --thanos-default-base-image=quay.io/thanos/thanos:v0.30.2
        ports:
        - containerPort: 8080
          name: metrics
        resources:
          {}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      serviceAccountName: prometheus-operator
