apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator
  labels: {{ include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus-operator
spec:
  type: "ClusterIP"
  ports:
  - name: metrics
    port: 8080
    targetPort: http
  selector: {{ include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus-operator
